spring:
  application:
    name: storeMVC
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi-Minh
        dialect: