spring:
  application:
    name: storeMVC
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi-Minh
        dialect: org.hibernate.dialect.SQLServerDialect
        connection.useUnicode: true
        connection.characterEncoding: UTF-8
        jdbc.time_zone: Asia/Ho_Chi_Minh
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
          springframework:
        security: DEBUG
initAdmin:
  default:
    username: ${SPRING_INIT_ADMIN_USERNAME}
    password: ${SPRING_INIT_ADMIN_PASSWORD}
    email: ${SPRING_INIT_ADMIN_EMAIL}